query GetAllPosts {
  posts(orderBy: publishedAt_DESC, first: 1000000000) {
    id
    slug
    title
    categories {
      id
      name
    }
    archive {
      id
      name
    }
    stage
    publishedAt
  }
}
