query GetAllPosts($skip: Int!, $first: Int!) {
  posts(orderBy: publishedAt_DESC, skip: $skip, first: $first) {
    id
    stage
    slug
    title
    publishedAt
    archive {
      id
      name
    }
    categories {
      id
      name
    }
  }
}
